// Generated by CoffeeScript 1.7.1
(function() {
  var buttons, draw_bar, draw_chart, legendChapters, legendTopics, legendTracks, menu_item;

  buttons = [
    {
      'title': 'Aktivität',
      'desc': 'Aktivität nach Kapiteln',
      'method': 'track_chapter'
    }, {
      'title': 'Anteile',
      'desc': 'Anteile im Gesamtüberblick',
      'method': 'track_topic'
    }, {
      'title': 'Zeitstrahl',
      'desc': 'Wortmeldungen/Aktivität über die Zeit',
      'method': 'track_commitments'
    }
  ];

  legendChapters = function(data) {
    var col, i, table, _i, _ref;
    table = $('<table></table>');
    for (i = _i = 0, _ref = data.length - 2; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      col = $('<tr></tr>');
      col.append($("<th>" + i + "</th>"));
      col.append($("<td>" + data[i].title + "</td>"));
      table.append(col);
    }
    $('#legend').append($("<h3>Chapters</h3>"));
    return $('#legend').append(table);
  };

  legendTracks = function(data, legend) {
    var col, i, table, _i, _ref;
    table = $('<table></table>');
    for (i = _i = 1, _ref = data.length - 1; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      col = $('<tr></tr>');
      col.append($("<th><div class='query-color' style='background-color:" + legend[data[i].title] + ";'></div></th>"));
      col.append($("<td>" + data[i].title + "</td>"));
      table.append(col);
    }
    return $('#legend').append(table);
  };

  legendTopics = function(data, master) {
    var col, host, table, _i, _len;
    table = $('<table></table>');
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      host = data[_i];
      if (master === host['master']) {
        col = $('<tr></tr>');
        col.append($("<td>" + host['chapter'] + "</td>"));
        table.append(col);
      }
    }
    $('#legend').append($("<h3>" + master + "</h3>"));
    return $('#legend').append(table);
  };

  draw_chart = function(json) {
    var areaChart;
    areaChart = new $jit.AreaChart({
      injectInto: 'infovis',
      animate: true,
      Margin: {
        top: 5,
        left: 5,
        right: 5,
        bottom: 5
      },
      labelOffset: 1,
      showAggregates: true,
      showLabels: true,
      type: 'stacked',
      Tips: {
        enable: true,
        onShow: function(tip, elem) {
          return tip.innerHTML = "<span><b>" + elem.name + "</b>: " + elem.value + "</span>";
        }
      }
    });
    areaChart.loadJSON(json);
    return areaChart.getLegend();
  };

  draw_bar = function(json, o, s) {
    var barChart;
    if (o == null) {
      o = 'horizontal';
    }
    if (s == null) {
      s = 'min';
    }
    barChart = new $jit.BarChart({
      injectInto: 'infovis',
      animate: true,
      orientation: o,
      barsOffset: 0.5,
      Margin: {
        top: 5,
        left: 5,
        right: 5,
        bottom: 5
      },
      labelOffset: 1,
      type: 'stacked',
      showAggregates: false,
      showLabels: true,
      Tips: {
        enable: true,
        onShow: function(tip, elem) {
          var sec;
          if (s === 'min') {
            sec = elem.value < 60 ? ' + ' + Math.round(elem.value) + 'sec</span>' : '</span>';
            return tip.innerHTML = "<span><b>" + elem.name + "</b>: " + Math.round(elem.value / 60) + "min" + sec;
          } else {
            return tip.innerHTML = "<span><b>" + elem.name + ":</b> " + Math.round(elem.value) + "%</span>";
          }
        }
      }
    });
    barChart.loadJSON(json);
    return barChart.getLegend();
  };

  menu_item = function(title, url) {
    var link, p;
    link = $("<a></a>");
    link.text(title);
    link.attr('id', url);
    link.click(function() {
      $('#infovis').empty();
      $('#legend').empty();
      $('#options').empty();
      $('#description').empty();
      return $.getJSON($(this).attr('id'), function(json) {
        var button, file, item, _i, _len;
        file = stats(json);
        for (_i = 0, _len = buttons.length; _i < _len; _i++) {
          button = buttons[_i];
          item = $('<button></button>');
          item.text(button['title']);
          item.attr('value', button['method']);
          item.attr('title', button['desc']);
          item.click(function() {
            $('#infovis').empty();
            $('#legend').empty();
            $('#description').empty();
            $('#description').append($("<p>" + ($(this).attr('title')) + "</p>"));
            return window[$(this).attr('value')](file);
          });
          $('#options').append(item);
        }
        window[buttons[0]['method']](file);
        $('#description').append($("<p>" + buttons[0]['title'] + "</p>"));
        $('#container').css('display', 'block');
        return $('#description').css('display', 'block');
      });
    });
    p = $('<p></p>');
    p.append(link);
    return $('#menu').append(p);
  };

  window.draw_bar = draw_bar;

  window.draw_chart = draw_chart;

  window.menu_item = menu_item;

  window.legendTopics = legendTopics;

  window.legendChapters = legendChapters;

  window.legendTracks = legendTracks;

  $(document).ready(function() {
    return menu();
  });

}).call(this);
