// Generated by CoffeeScript 1.7.1
(function() {
  var Chapter, File, Track, files, fn, menu, stats, track_chapter, track_commitments, track_topic;

  files = [];

  files.push('data/fs133-ich-werde-noch-meinen-kindern-davon-erzaehlen.json');

  files.push('data/fs132-005-clemens.json');

  files.push('data/SZ011.json');

  files.push('data/lnp102-nur-wenige-admins-haben-zugriff.json');

  Chapter = (function() {
    function Chapter(title, obj) {
      this.title = title;
      this.obj = obj;
    }

    Chapter.prototype.start = function() {
      return parseFloat(this.obj['start_sec']);
    };

    return Chapter;

  })();

  Track = (function() {
    var topics;

    topics = {};

    Track.prototype.topic = function(title) {
      if (!topics[this.title]) {
        topics[this.title] = [];
      }
      return topics[this.title].push(title);
    };

    Track.prototype.topic = function() {
      return topics[this.title];
    };

    function Track(title, activity, length) {
      this.title = title;
      this.activity = activity;
      this.length = length;
    }

    Track.prototype.total = function(start, end) {
      var time;
      if (start == null) {
        start = 0;
      }
      if (end == null) {
        end = this.length;
      }
      time = 0;
      $.each(this.activity, function(index, value) {
        if (parseFloat(value[0]) >= start && parseFloat(value[1]) <= end) {
          return time += parseFloat(value[1]) - parseFloat(value[0]);
        }
      });
      return time;
    };

    Track.prototype.count = function(start, end) {
      var i;
      if (end == null) {
        end = this.length;
      }
      i = 0;
      $.each(this.activity, function(index, value) {
        if (parseFloat(value[0]) >= start && parseFloat(value[1]) <= end) {
          return i += 1;
        }
      });
      return i;
    };

    Track.prototype.percent = function(start, end) {
      if (end == null) {
        end = this.length;
      }
      return 100 * (this.total(start, end) / end);
    };

    return Track;

  })();

  File = (function() {
    function File(url) {
      var chapters, tracks;
      this.url = url;
      chapters = [];
      tracks = [];
      $.getJSON(this.url, function(json) {
        $.each(json['chapters'].sort(fn), function(index, value) {
          return chapters.push(new Chapter(value['title'], value));
        });
        chapters.push(new Chapter('End', {
          'start_sec': json['length']
        }));
        return $.each(json['statistics']['tracks'], function(index, value) {
          if (value['activity']) {
            return tracks.push(new Track(value['identifier'], value['activity'], parseFloat(json['multi_input_files'][index]['input_length'])));
          }
        });
      });
      this.chapters = chapters;
      this.tracks = tracks;
    }

    return File;

  })();

  menu = function() {
    var i, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = files.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      _results.push($.getJSON(files[i], function(json) {
        return menu_item(json['metadata']['title'], "data/" + json['output_basename'] + ".json");
      }));
    }
    return _results;
  };

  stats = function(url) {
    return new File(url);
  };

  track_commitments = function(file) {
    var data, labels, legend, quarter1, quarter2, quarter3, quarter4, track, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1, _ref2, _ref3;
    labels = [];
    quarter1 = [];
    quarter2 = [];
    quarter3 = [];
    quarter4 = [];
    _ref = file.tracks;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      track = _ref[_i];
      labels.push(track.title);
      quarter1.push(track.count(0, track.length / 4));
    }
    _ref1 = file.tracks;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      track = _ref1[_j];
      quarter2.push(track.count(track.length / 4, track.length / 3));
    }
    _ref2 = file.tracks;
    for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
      track = _ref2[_k];
      quarter3.push(track.count(track.length / 3, track.length / 2));
    }
    _ref3 = file.tracks;
    for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
      track = _ref3[_l];
      quarter4.push(track.count(track.length / 2, track.length));
    }
    data = {
      'label': labels,
      'values': [
        {
          'label': '¼',
          'values': quarter1
        }, {
          'label': '½',
          'values': quarter2
        }, {
          'label': '¾',
          'values': quarter3
        }, {
          'label': '1',
          'values': quarter4
        }
      ]
    };
    legend = draw_chart(data);
    return legendTracks(file.tracks, legend);
  };

  track_topic = function(file) {
    var data, hosts, i, labels, legend, t, track, values, _i, _j, _k, _l, _len, _len1, _len2, _ref, _ref1, _ref2, _ref3, _results;
    t = file.tracks[0];
    labels = [];
    values = [];
    hosts = [];
    _ref = file.tracks;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      track = _ref[_i];
      values.push(track.percent(0));
      labels.push(track.title);
    }
    data = {
      'label': labels,
      'values': [
        {
          'label': [],
          'values': values
        }
      ]
    };
    legend = draw_bar(data, 'vertical');
    for (i = _j = 0, _ref1 = file.chapters.length - 2; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
      _ref2 = file.tracks;
      for (_k = 0, _len1 = _ref2.length; _k < _len1; _k++) {
        track = _ref2[_k];
        if (track.percent(file.chapters[i].start(), file.chapters[i + 1].start()) > t.percent(file.chapters[i].start(), file.chapters[i + 1].start())) {
          t = track;
        }
      }
      hosts.push({
        'chapter': file.chapters[i].title,
        'master': t.title
      });
    }
    legendTracks(file.tracks, legend);
    _ref3 = file.tracks;
    _results = [];
    for (_l = 0, _len2 = _ref3.length; _l < _len2; _l++) {
      track = _ref3[_l];
      _results.push(legendTopics(hosts, track.title));
    }
    return _results;
  };

  track_chapter = function(file) {
    var data, i, labels, legend, t, track, v, values, _i, _j, _k, _len, _len1, _ref, _ref1, _ref2;
    t = file.tracks[0];
    labels = [];
    values = [];
    for (i = _i = 0, _ref = file.chapters.length - 2; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      v = [];
      _ref1 = file.tracks;
      for (_j = 0, _len = _ref1.length; _j < _len; _j++) {
        track = _ref1[_j];
        if (track.percent(file.chapters[i].start(), file.chapters[i + 1].start()) > t.percent(file.chapters[i].start(), file.chapters[i + 1].start())) {
          t = track;
        }
        v.push(track.percent(file.chapters[i].start(), file.chapters[i + 1].start()));
      }
      values.push({
        'label': i,
        'values': v
      });
    }
    _ref2 = file.tracks;
    for (_k = 0, _len1 = _ref2.length; _k < _len1; _k++) {
      track = _ref2[_k];
      labels.push(track.title);
    }
    data = {
      'label': labels,
      'values': values
    };
    legend = draw_bar(data);
    legendTracks(file.tracks, legend);
    return legendChapters(file.chapters);
  };

  window.track_chapter = track_chapter;

  window.track_commitments = track_commitments;

  window.track_topic = track_topic;

  window.menu = menu;

  window.stats = stats;

  fn = function(a, b) {
    if (parseFloat(a['start_sec']) < parseFloat(b['start_sec'])) {
      return -1;
    } else {
      return 1;
    }
  };

}).call(this);
